# -*- coding: utf-8 -*-
"""Ensemble .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pecIqR6s9BSpRctP7AKBbhY1eIBsY-PQ
"""

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split,cross_val_score,GridSearchCV
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_breast_cancer

def evaluate_classifier(clf, x_train, y_train, x_test, y_test, name="model"):
    clf.fit(x_train, y_train)
    y_pred = clf.predict(x_test)
    print(f"\n{name}")
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred, digits=4))
    return {
        "accuracy": accuracy_score(y_test, y_pred),
        "precision": precision_score(y_test, y_pred, average='weighted'),
        "recall": recall_score(y_test, y_pred, average='weighted'),
        "f1_score": f1_score(y_test, y_pred, average='weighted')
    }

data=load_breast_cancer()
x,y=data.data,data.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

dt=DecisionTreeClassifier(random_state=42)
dt.fit(x_train,y_train)
dt_metrics=evaluate_classifier(dt,x_train,y_train,x_test,y_test,"Decision Tree")
print("Decision Tree Metrics")
print(dt_metrics)

n_estimators=[1,5,10,50,100]
rf_metrics={}
for n in n_estimators:
  rf=RandomForestClassifier(n_estimators=n,random_state=42)
  rf.fit(x_train,y_train)
  rf_metrics[n]=evaluate_classifier(rf,x_train,y_train,x_test,y_test,f"Random Forest({n})")
print("\nRandom Forest Metrics")
for n,metrics in rf_metrics.items():
  print(f"{n} estimators={n}:{metrics}")

import matplotlib.pyplot as plt

n_estimators = list(rf_metrics.keys())
accuracy_scores = [metrics['accuracy'] for metrics in rf_metrics.values()]

plt.figure(figsize=(10, 6))
plt.plot(n_estimators, accuracy_scores, marker='o', label='Random Forest')

# Add Decision Tree accuracy
dt_accuracy = dt_metrics['accuracy']
plt.axhline(y=dt_accuracy, color='r', linestyle='--', label='Decision Tree')


plt.title('Classifier Accuracy vs. Number of Estimators (Random Forest)')
plt.xlabel('Number of Estimators')
plt.ylabel('Accuracy')
plt.grid(True)
plt.legend() # Add legend to show labels
plt.show()

from sklearn.ensemble import VotingClassifier

# Assuming rf_metrics has the best Random Forest model's accuracy (e.g., for n=100)
# You might want to choose the best performing RF model based on rf_metrics
best_rf = RandomForestClassifier(n_estimators=100, random_state=42) # Using the best from the previous test
best_rf.fit(x_train, y_train)


# Max Voting
# Create a list of estimators (your trained models)
estimators = [('dt', dt), ('rf', best_rf)]

# Create the VotingClassifier with 'hard' voting
max_voting_clf = VotingClassifier(estimators=estimators, voting='hard')

# Evaluate the Max Voting classifier
max_voting_metrics = evaluate_classifier(max_voting_clf, x_train, y_train, x_test, y_test, "Max Voting")
print("Max Voting Metrics:", max_voting_metrics)


# Average Voting (for probability-based classifiers)
# Note: Decision Tree and Random Forest provide predict_proba
# Create the VotingClassifier with 'soft' voting
avg_voting_clf = VotingClassifier(estimators=estimators, voting='soft')

# Evaluate the Average Voting classifier
avg_voting_metrics = evaluate_classifier(avg_voting_clf, x_train, y_train, x_test, y_test, "Average Voting")
print("Average Voting Metrics:", avg_voting_metrics)

# Weighted Average Voting
# You can assign weights based on the performance of individual models
# Let's use accuracy as weights for this example
dt_accuracy = dt_metrics['accuracy']
rf_accuracy = rf_metrics[100]['accuracy'] # Using accuracy of RF with 100 estimators as an example

weights = [dt_accuracy, rf_accuracy]

# Create the VotingClassifier with 'soft' voting and weights
weighted_avg_voting_clf = VotingClassifier(estimators=estimators, voting='soft', weights=weights)

# Evaluate the Weighted Average Voting classifier
weighted_avg_voting_metrics = evaluate_classifier(weighted_avg_voting_clf, x_train, y_train, x_test, y_test, "Weighted Average Voting")
print("Weighted Average Voting Metrics:", weighted_avg_voting_metrics)

import matplotlib.pyplot as plt

voting_types = ['Max Voting', 'Average Voting', 'Weighted Average Voting']
voting_accuracies = [max_voting_metrics['accuracy'], avg_voting_metrics['accuracy'], weighted_avg_voting_metrics['accuracy']]

plt.figure(figsize=(8, 6))
plt.bar(voting_types, voting_accuracies, color=['blue', 'green', 'orange'])
plt.ylabel('Accuracy')
plt.title('Accuracy Comparison of Different Voting Methods')
plt.ylim(0.9, 1.0) # Set a reasonable y-limit based on the current accuracies
plt.show()

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer

# Reload data and split for clarity, although already done in the first cell
data = load_breast_cancer()
x, y = data.data, data.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# Define base learners
dt_clf = DecisionTreeClassifier(random_state=42)
lr_clf = LogisticRegression(random_state=42, solver='liblinear') # Use liblinear for simplicity
knn_clf = KNeighborsClassifier(n_neighbors=5) # Using default n_neighbors

# Train base learners (although VotingClassifier does this internally,
# it's good practice to have them defined and potentially evaluated individually first)
dt_clf.fit(x_train, y_train)
lr_clf.fit(x_train, y_train)
knn_clf.fit(x_train, y_train)

# Create list of estimators
estimators = [('dt', dt_clf), ('lr', lr_clf), ('knn', knn_clf)]

# Hard Voting
hard_voting_clf = VotingClassifier(estimators=estimators, voting='hard')
hard_voting_metrics = evaluate_classifier(hard_voting_clf, x_train, y_train, x_test, y_test, "Hard Voting (DT, LR, KNN)")
print("Hard Voting Metrics (DT, LR, KNN):", hard_voting_metrics)

# Soft Voting (Requires base classifiers to support predict_proba)
# Logistic Regression and KNN support predict_proba. Decision Tree also supports it.
soft_voting_clf = VotingClassifier(estimators=estimators, voting='soft')
soft_voting_metrics = evaluate_classifier(soft_voting_clf, x_train, y_train, x_test, y_test, "Soft Voting (DT, LR, KNN)")
print("Soft Voting Metrics (DT, LR, KNN):", soft_voting_metrics)

# Optional: Weighted Soft Voting (You can adjust weights based on individual classifier performance)
# Let's use equal weights for simplicity here, which is equivalent to simple soft voting.
# For demonstration, you could calculate and use actual performance metrics as weights.
# For example:
# dt_acc = dt_clf.score(x_test, y_test)
# lr_acc = lr_clf.score(x_test, y_test)
# knn_acc = knn_clf.score(x_test, y_test)
# weights = [dt_acc, lr_acc, knn_acc]
# weighted_soft_voting_clf = VotingClassifier(estimators=estimators, voting='soft', weights=weights)
# weighted_soft_voting_metrics = evaluate_classifier(weighted_soft_voting_clf, x_train, y_train, x_test, y_test, "Weighted Soft Voting (DT, LR, KNN)")
# print("Weighted Soft Voting Metrics (DT, LR, KNN):", weighted_soft_voting_metrics)

# Experiment with random_state
random_states_list = [0, 42, 123, 456, 789] # Experiment with a few different random states
rf_random_state_metrics = {}

for rs in random_states_list:
    rf = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=rs) # Use fixed n_estimators and max_depth
    rf_random_state_metrics[rs] = evaluate_classifier(rf, x_train, y_train, x_test, y_test, f"Random Forest (random_state={rs})")

print("\nRandom Forest Metrics for varying random_state:")
for rs, metrics in rf_random_state_metrics.items():
    print(f"random_state={rs}: {metrics}")

# Experiment with max_depth
max_depth_list = [1, 5, 10, 20, None] # None means unlimited depth
rf_max_depth_metrics = {}

for depth in max_depth_list:
    rf = RandomForestClassifier(n_estimators=100, max_depth=depth, random_state=42) # Use a fixed n_estimators, e.g., 100
    rf_max_depth_metrics[depth] = evaluate_classifier(rf, x_train, y_train, x_test, y_test, f"Random Forest (max_depth={depth})")

print("\nRandom Forest Metrics for varying max_depth:")
for depth, metrics in rf_max_depth_metrics.items():
    print(f"max_depth={depth}: {metrics}")

# Experiment with n_estimators
n_estimators_list = [1, 5, 10, 20, 50, 100, 200, 500]
rf_n_estimators_metrics = {}

for n in n_estimators_list:
    rf = RandomForestClassifier(n_estimators=n, random_state=42)
    rf_n_estimators_metrics[n] = evaluate_classifier(rf, x_train, y_train, x_test, y_test, f"Random Forest ({n} estimators)")

print("\nRandom Forest Metrics for varying n_estimators:")
for n, metrics in rf_n_estimators_metrics.items():
    print(f"{n} estimators: {metrics}")

import matplotlib.pyplot as plt

# Prepare data for plotting
n_estimators_values = list(rf_n_estimators_metrics.keys())
accuracy_scores = [metrics['accuracy'] for metrics in rf_n_estimators_metrics.values()]
precision_scores = [metrics['precision'] for metrics in rf_n_estimators_metrics.values()]
recall_scores = [metrics['recall'] for metrics in rf_n_estimators_metrics.values()]
f1_scores = [metrics['f1_score'] for metrics in rf_n_estimators_metrics.values()]

# Plot Accuracy vs. Number of Estimators
plt.figure(figsize=(10, 6))
plt.plot(n_estimators_values, accuracy_scores, marker='o')
plt.xscale('log') # Use log scale for better visualization of varying n_estimators
plt.title('Random Forest Performance vs. Number of Estimators')
plt.xlabel('Number of Estimators')
plt.ylabel('Accuracy')
plt.grid(True)
plt.show()

# Plot other metrics if desired (e.g., Precision, Recall, F1-score)
plt.figure(figsize=(10, 6))
plt.plot(n_estimators_values, precision_scores, marker='o', label='Precision')
plt.plot(n_estimators_values, recall_scores, marker='o', label='Recall')
plt.plot(n_estimators_values, f1_scores, marker='o', label='F1-score')
plt.xscale('log')
plt.title('Random Forest Performance vs. Number of Estimators')
plt.xlabel('Number of Estimators')
plt.ylabel('Score')
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt

voting_types = ['Hard Voting', 'Soft Voting']
voting_accuracies = [hard_voting_metrics['accuracy'], soft_voting_metrics['accuracy']]

plt.figure(figsize=(8, 6))
plt.bar(voting_types, voting_accuracies, color=['purple', 'brown'])
plt.ylabel('Accuracy')
plt.title('Accuracy Comparison of Hard and Soft Voting (DT, LR, KNN)')
plt.ylim(min(voting_accuracies) * 0.95, max(voting_accuracies) * 1.05) # Adjust y-limit based on current accuracies
plt.show()

